# Generated by Django 2.1.7 on 2019-03-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='select1',
            new_name='select_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='select2',
            new_name='select_2',
        ),
    ]
