# Generated by Django 2.1.7 on 2019-03-20 16:57

import choice.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_auto_20190320_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=choice.models.choice_image_path),
        ),
        migrations.AddField(
            model_name='question',
            name='img_2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=choice.models.choice_image_path),
        ),
    ]
